---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-install"
      label: "Install"
      solveButton: false
    - name: "02-login"
      label: "Login"
      solveButton: false
    - name: "03-enable"
      label: "Enable"
      solveButton: false
    - name: "04-review"
      label: "Review"
      solveButton: false
    - name: "05-recording"
      label: "Recording"
      solveButton: false
    - name: "06-reviewing"
      label: "Reviewing"
      solveButton: false
    - name: "07-review-cli"
      label: "Review Cli"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty
  - name: "Web Console"
    url: https://cockpit-${guid}.${domain}/
